### ISSUE TITLE
go run . - do not work as expected

### ISSUE THREAD

**Issue by UvisG** [koor-tech/extended-ceph-exporter#12]
Hi,

Today tried to install and I am stuck at "go run ." When I execute it I get error:
FATA[0000] required flag rgw-host not set               
exit status 1

Tried also by using flags. Example below
go run . --rgw-host "here-comes-my-rgw-url" --rgw-access-key "here-comes-my-access-key" --rgw-secret-key "here-comes-my-secret"

and I get this time error this:
FATA[0000] flag rgw-user not found during lookup        
exit status 1

root@prometheus:/etc/prometheus/extended-ceph-exporter# go version
go version go1.19 linux/amd64

Help please!

**Comment by galexrt** [comment]
@UvisG We have fixed the flags issue you were encountering, please try again with the latest code and let us know if that fixes your issue.
