### ISSUE TITLE
Allow use of existing secrets

### ISSUE THREAD

**Issue by jon-rei** [koor-tech/extended-ceph-exporter#53]
It would be great if we could use existing secrets for the exporter.
In our environment we use SealedSecrets to create our secrets. So it would be great if an existing secret could be passed to the helm chart for the `rgw` configuration.

**Comment by galexrt** [comment]
@jon-rei Good point, I think we will probably make it so that if a secret is given

**Comment by galexrt** [comment]
@jon-rei please try with the latest helm chart version 1.3.0 and let us know if that works for you

**Comment by jon-rei** [comment]
Hi @galexrt, I've just deployed the new version on our cluster and it works, thanks for the quick implementation.
